### ISSUE TITLE
Streaming totally breaks down after about 20 minutes of use

### ISSUE THREAD

**Issue by darrenhaken** [streetpea/chiaki-ng#103]
I’m using Chiaki4deck on my Steam OLED, I used to use it flawlessly on my LCD model. 

However, with the oled after around 20 minutes I receive severe stuttering, green and white screens. Prior to that performance is flawless. If I close the session (even with leaving the ps5 switched on) and then reconnect a new session it returns to normal.

I am running it at 720p, 60fps and I’ve tried various buffer and audio settings from the defaults and higher. 

Do you have any idea what might be causing this?

**Comment by johnhste** [comment]
I also have this issue with my remote play to my PS4.
I go to the main screen it will clear up for a while. 
I don't always have to reconnect.

**Comment by streetpea** [comment]
There is an alternate native build of chiaki4deck available from @tvidal-net here: https://github.com/tvidal-net/chiaki4deck-build that some users have reported fixes this issue for them versus using a flatpak build. It might be worth it to try out that build and see if it performs any better for you.

**Comment by crossedstar** [comment]
@darrenhaken @johnhste @streetpea 

I found this post late last night and tried it on my steam deck. It seemed to have made things a lot stable with streaming from Chiaki on my Deck OLED:

```
Open Kate (text editor) and simply copy these lines of code into lines 1 and 2

`@nClientDownloadEnableHTTP2PlatformLinux 0`

`@fDownloadRateImprovementToAddAnotherConnection 1.0`

and save as `steam_dev.cfg` in the `/home/deck/.steam/steam/` directory.

```

I found the solution on this Reddit post. YMMV
https://www.reddit.com/r/SteamDeck/s/IPG6E4Vjvd

**Comment by hvmzx** [comment]
Thank you @crossedstar , this fixed my issues on SD OLED. No more glitches with chiaki4deck, I couldn't run at 720@30 and now run at 1080@60 30k mbps with no issue whatsoever.

**Comment by plexecutor** [comment]
This 'fix' didn't fix anything for me. Same problem where the stream is fine for about 20 minutes and then the audio and video start to stutter before it either 1) entirely freezes or 2) i lose all controls but the audio and video continue to stream fine.

**Comment by hvmzx** [comment]
Spoke too soon, it doesn't work anymore. So there is definitely something wrong with the OLED model and the way it handles wifi

**Comment by plexecutor** [comment]
Has anyone tried testing the latest Steam OS preview builds on their OLED? The last two releases have mentioned fixing WiFi related issues.

**Comment by iTsMute** [comment]
Having the same issue. I've also noticed my total system power is quite high at 8 watts. Last night it was at 5 watts and running fine. I went from 10 hours of play time to 5 hours from 70%

**Comment by darrenhaken** [comment]
For context, the only way I managed to fix this:

- my router has the ability for a separate Wifi 6 SSID (the other SSID is 2 and 5ghz combined).
- if I connect the steam deck to the wifi 6 ssid then it behaves as stable as my LCD model did. Very stable.

**Comment by iTsMute** [comment]
> For context, the only way I managed to fix this:
> 
>     * my router has the ability for a separate Wifi 6 SSID (the other SSID is 2 and 5ghz combined).
> 
>     * if I connect the steam deck to the wifi 6 ssid then it behaves as stable as my LCD model did. Very stable.

Hmmm... I have my ssid separated for 2.4ghz and 5ghz but both are wifi 6. Both work fine but after about 15 to 20 mins fps drops occur and a grey/green mess comes on to the screen. I can turn wifi 6 off and test to see if it continues or not. 

The other thing I'm seeing is high total system power at 8w. I've seen it go as low as 5.4w and have no issues. Not sure what's going on here tbh.

**Comment by plexecutor** [comment]
> > Has anyone tried testing the latest Steam OS preview builds on their OLED? The last two releases have mentioned fixing WiFi related issues.
> 
> Can you share the release notes where it says it?

SteamOS 3.5.13 Preview: Here Be Dragons
Note: This update is for the Steam Deck Preview channel, and includes new features that are still being tested. You can opt into this in Settings > System > System Update Channel.

General
Added a slider to control the brightness of the Status LED (Charger LED). This setting can be found under Settings -> Display.
**Fixed a case where wifi would fail to connect in certain conditions**
Fixed HDR on some external DisplayPort displays being slightly desaturated


SteamOS 3.5.12 Preview: Elves in Tuxedos
Note: This update is for the Steam Deck Preview channel, and includes new features that are still being tested. You can opt into this in Settings > System > System Update Channel.

General
Added support for the HyperX Clutch Gladiate controllers
Fixed a system restart when Joy-Con controllers are connected
**Fixed a WiFi crash occurring where certain bands would cause the driver to attempt to set an incorrect spatial stream count**

**Comment by plexecutor** [comment]
> For context, the only way I managed to fix this:
> 
> * my router has the ability for a separate Wifi 6 SSID (the other SSID is 2 and 5ghz combined).
> * if I connect the steam deck to the wifi 6 ssid then it behaves as stable as my LCD model did. Very stable.

My WiFi AP only does 2.4ghz or 5ghz WiFi 5.

**Comment by hvmzx** [comment]
> Has anyone tried testing the latest Steam OS preview builds on their OLED? The last two releases have mentioned fixing WiFi related issues.

- I tried this on my OLED, the latest SteamOS preview and it didn't fix anything.
- I also tried separating the 2.4Ghz and 5Ghz ssid's, and it didn't fix the freezing.
- I also tried this https://github.com/streetpea/chiaki4deck/issues/103#issuecomment-1846414293 and it didn't work.

Hopefully we figure this OLED thing out

**Comment by plexecutor** [comment]
> > Has anyone tried testing the latest Steam OS preview builds on their OLED? The last two releases have mentioned fixing WiFi related issues.
> 
> * I tried this on my OLED, the latest SteamOS preview and it didn't fix anything.
> * I also tried separating the 2.4Ghz and 5Ghz ssid's, and it didn't fix the freezing.
> * I also tried this [Streaming totally breaks down after about 20 minutes of use #103 (comment)](https://github.com/streetpea/chiaki4deck/issues/103#issuecomment-1846414293) and it didn't work.
> 
> Hopefully we figure this OLED thing out

Thanks for testing. Definitely agree, we need to get this figured out. I’m willing to help by gathering any logs needed or testing dev/debug builds of chiaki4deck.

**Comment by hvmzx** [comment]
Same, down to help as much as possible.

**Comment by plexecutor** [comment]
I tested during two hour long sessions using a USB-C to Ethernet adapter on my OLED deck and the stream was rock solid with no glitches, freezes, or crashes. Definitely seems like a wifi issue specific to the OLED model. I also did some more testing where I segregated my 2.4 and 5ghz radios on two SSIDs rather than consolidated as I normally run them but the stream was still crapping out within 5-10 minutes when connected to the 5ghz SSID.

**Comment by darrenhaken** [comment]
I read somewhere online that the new WiFi chipset may have driver issues. I'm suspecting it's that. WiFi 6 seems to stabilise it for me but it's a pain. I can even do 1080p

**Comment by iTsMute** [comment]
> I read somewhere online that the new WiFi chipset may have driver issues. I'm suspecting it's that. WiFi 6 seems to stabilise it for me but it's a pain. I can even do 1080p

I've tested wifi 5 and 6 and run into the same issue. I've also enabled and disabled the 160mhz band and the power managment mode for 5ghz band. I've tested separate 2.4 and 5ghz band. The only time this issue is happening for me with chiaki is when I am using the new hdr feature. If hdr feature is off I have no issues with any of these settings on my network. It will work fine with wifi 5 or 6. 2.4ghz or 5ghz. 160mhz disabled or enabled.

I don't doubt the wifi chip can be having issues. From my personal testing my wifi chip does not seem to be the issue. Otherwise it would be given me the same problems regardless if hdr was on or off and that is not the case for me.

**Comment by RainrZufall** [comment]
For me the problem only occurs after standby.
When the problem occurs, I turn off the wifi on the Steam Deck, count to 8 and turn the wifi back on. After that I don't have any problems anymore, no matter how long I play.

**Comment by streetpea** [comment]
It may be also worth trying the appimage and seeing if you have any better luck with that (vaapi can now also be enabled in the appimage as of the latest release)

**Comment by Sweetcheezus** [comment]
What's really odd is that I'm streaming at 720p and I tried 10000 bitrate for video and it was choppy. I tried 20000, same thing. I went all the way up to 65000 and for whatever reason it's a lot smoother but not perfect. I have no logical explanation as to why or how this would work but it helped me. Try cranking the video bitrate way up. It's worth a shot.

**Comment by hasskhan** [comment]
Guy's did anyone found a solution to this ? It's March and still after some time the frame rates goes from 60 to even 20 and 10 . Untill I put the deck in offline or restart it . This is so annoying

**Comment by RainrZufall** [comment]
> Guy's did anyone found a solution to this ? It's March and still after some time the frame rates goes from 60 to even 20 and 10 . Untill I put the deck in offline or restart it . This is so annoying

Maybe the problem is related to Steamos rather than C4D?
I also have to deactivating WiFi for about 5-8 seconds. Afterwards I can continue playing immediately and without any problems.

**Comment by Odizinne** [comment]
> For me the problem only occurs after standby. When the problem occurs, I turn off the wifi on the Steam Deck, count to 8 and turn the wifi back on. After that I don't have any problems anymore, no matter how long I play.

Exact same behavior for me, but with steam remote play. Exact same way to fix it.

Pretty sure this issue is not related to C4D. Probably has to do with the OLED chip / drivers.
